#:schema node_modules/wrangler/config-schema.json
name = "kroma"
pages_build_output_dir = "dist/public"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[vars]
# Add any environment variables here if needed
